name: APK-TV Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 👇 在这里写你的 子分支名称（必须改）
          ref: fongmi

      - name: Clone Project
        run: git clone -b dev --depth=1 https://github.com/Zhongjie268/TV.git

      - name: DIY
        run: |
          chmod +x diy-TV.sh
          bash ${{ github.workspace }}/diy-TV.sh

      - name: Build With Gradle
        run: |
          cd ${{ github.workspace }}/TV
          chmod +x gradlew
          ./gradlew assembleleanbackRelease --build-cache --parallel --daemon --warning-mode all

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find ${{ github.workspace }}/TV -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      # 👇 已升级到 v4，修复弃用错误
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
