name: APK-TV Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 关键：直接克隆你要编译的仓库 + 分支
      - name: Clone 你的 fongmi 分支
        run: git clone -b fongmi --depth=1 https://github.com/Zhongjie268/TV.git

      - name: 编译 APK
        run: |
          cd TV
          chmod +x gradlew
          ./gradlew assembleleanbackRelease --build-cache --parallel --daemon --warning-mode all

      - name: 打包 APK
        run: |
          mkdir -p apk
          find TV -name "*.apk" -exec mv {} apk/ \;

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: tvbox-fongmi
          path: apk/*
