name: APK-TV Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 关键：拉取你自己的 fongmi 分支
          ref: fongmi

      - name: 赋予执行权限
        run: |
          chmod +x gradlew
          
      - name: 开始编译 APK
        run: |
          ./gradlew assembleleanbackRelease --build-cache --parallel --daemon --warning-mode all

      - name: 整理 APK 文件
        run: |
          mkdir -p apk
          find . -name "*.apk" -exec mv {} apk/ \;

      - name: 上传 APK 成品
        uses: actions/upload-artifact@v4
        with:
          name: tvbox-fongmi-apk
          path: apk/*
